spring.application.name=notification-service
server.port=8086

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka:8761/eureka/}
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
