global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: spring-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - eureka:8761
          - gateway-service:9000
          - authentication-service:8091
          - pelanggan:8084
          - produk:8081
          - order-service:8083
          - notification-service:8086
          - produser:8087
          - consumer:8085
