server.port=8084
spring.application.name=order

# ================= DB =================
spring.datasource.url=jdbc:h2:mem:order;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# ================= EUREKA =================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ================= RABBITMQ =================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ================= EMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jasmine@gmail.com
spring.mail.password=APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true